vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: /build/images
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        avatars:
            uri_prefix: /build/avatars
            upload_destination: '%kernel.project_dir%/public/build/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
